### ISSUE TITLE
Non-portable color escape codes

### ISSUE THREAD

**Issue by englishm** [hannob/bashcheck#3]
I assume that the escape codes in this script display very nice colors on your platform, but they do not appear correctly in my terminal.

![3__ello__tmux_](https://cloud.githubusercontent.com/assets/1165411/4432499/aa93925c-4697-11e4-935a-51ed48a54354.png)

Are they necessary? I'll send a separate pull request to remove them.

**Comment by hannob** [comment]
I find it quite handy to have a colored output, so I won't merge that.

(out of curiosity: what platform is that?)

**Comment by englishm** [comment]
Totally fair. 
I don't know enough right now to know why they they wouldn't work for me or I'd send a PR to fix them, too.

This platform is:
OS X 10.9.5 w/ iTerm2 (it also appears this way in Terminal).
I've applied a few of Chet's patches to my bash at this point.
Color for other programs works correctly (e.g. `ls -G`)

**Comment by hannob** [comment]
just googled that this might be more portable, can you try?
echo -e "\033[92m test"

**Comment by englishm** [comment]
Yes! That does work for me.
